const text =
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis \n       
  sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem \n
  
  
  ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, \n 
  
  
  lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit \n 
  
  
  
  cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor \n
  
  
  
  
  nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, \n
  
  
  
  
  hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat.\n 
  Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae blandit metus. Donec quis lacinia leo. Phasellus convallis arcu sem, id porttitor elit tempor nec. Nunc enim justo, lobortis sit amet sem eu, pellentesque fringilla nisl. Pellentesque maximus est a lorem sodales vulputate. Praesent scelerisque id nisi sed volutpat. Ut sed aliquam enim, hendrerit cursus felis. Sed sagittis risus eros, quis auctor quam sagittis at.`;

  export default text;